/**
* p4firewall API generated from p4firewall.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "FlowDirectionJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

FlowDirectionJsonObject::FlowDirectionJsonObject() {
  m_srcInterfaceIsSet = false;
  m_dstInterfaceIsSet = false;
  m_directionIsSet = false;
}

FlowDirectionJsonObject::FlowDirectionJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_srcInterfaceIsSet = false;
  m_dstInterfaceIsSet = false;
  m_directionIsSet = false;


  if (val.count("srcInterface")) {
    setSrcInterface(val.at("srcInterface").get<std::string>());
  }

  if (val.count("dstInterface")) {
    setDstInterface(val.at("dstInterface").get<std::string>());
  }

  if (val.count("direction")) {
    setDirection(val.at("direction").get<uint8_t>());
  }
}

nlohmann::json FlowDirectionJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_srcInterfaceIsSet) {
    val["srcInterface"] = m_srcInterface;
  }

  if (m_dstInterfaceIsSet) {
    val["dstInterface"] = m_dstInterface;
  }

  if (m_directionIsSet) {
    val["direction"] = m_direction;
  }

  return val;
}

std::string FlowDirectionJsonObject::getSrcInterface() const {
  return m_srcInterface;
}

void FlowDirectionJsonObject::setSrcInterface(std::string value) {
  m_srcInterface = value;
  m_srcInterfaceIsSet = true;
}

bool FlowDirectionJsonObject::srcInterfaceIsSet() const {
  return m_srcInterfaceIsSet;
}



std::string FlowDirectionJsonObject::getDstInterface() const {
  return m_dstInterface;
}

void FlowDirectionJsonObject::setDstInterface(std::string value) {
  m_dstInterface = value;
  m_dstInterfaceIsSet = true;
}

bool FlowDirectionJsonObject::dstInterfaceIsSet() const {
  return m_dstInterfaceIsSet;
}



uint8_t FlowDirectionJsonObject::getDirection() const {
  return m_direction;
}

void FlowDirectionJsonObject::setDirection(uint8_t value) {
  m_direction = value;
  m_directionIsSet = true;
}

bool FlowDirectionJsonObject::directionIsSet() const {
  return m_directionIsSet;
}

void FlowDirectionJsonObject::unsetDirection() {
  m_directionIsSet = false;
}


}
}
}

