/**
* p4firewall API generated from p4firewall.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* FlowDirectionJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  FlowDirectionJsonObject : public JsonObjectBase {
public:
  FlowDirectionJsonObject();
  FlowDirectionJsonObject(const nlohmann::json &json);
  ~FlowDirectionJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// In port.
  /// </summary>
  std::string getSrcInterface() const;
  void setSrcInterface(std::string value);
  bool srcInterfaceIsSet() const;

  /// <summary>
  /// Out port.
  /// </summary>
  std::string getDstInterface() const;
  void setDstInterface(std::string value);
  bool dstInterfaceIsSet() const;

  /// <summary>
  /// Inboud or outbound
  /// </summary>
  uint8_t getDirection() const;
  void setDirection(uint8_t value);
  bool directionIsSet() const;
  void unsetDirection();

private:
  std::string m_srcInterface;
  bool m_srcInterfaceIsSet;
  std::string m_dstInterface;
  bool m_dstInterfaceIsSet;
  uint8_t m_direction;
  bool m_directionIsSet;
};

}
}
}

