/**
* p4firewall API generated from p4firewall.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "RouteJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

RouteJsonObject::RouteJsonObject() {
  m_addressIsSet = false;
  m_macIsSet = false;
  m_interfaceIsSet = false;
}

RouteJsonObject::RouteJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_addressIsSet = false;
  m_macIsSet = false;
  m_interfaceIsSet = false;


  if (val.count("address")) {
    setAddress(val.at("address").get<std::string>());
  }

  if (val.count("mac")) {
    setMac(val.at("mac").get<std::string>());
  }

  if (val.count("interface")) {
    setInterface(val.at("interface").get<std::string>());
  }
}

nlohmann::json RouteJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_addressIsSet) {
    val["address"] = m_address;
  }

  if (m_macIsSet) {
    val["mac"] = m_mac;
  }

  if (m_interfaceIsSet) {
    val["interface"] = m_interface;
  }

  return val;
}

std::string RouteJsonObject::getAddress() const {
  return m_address;
}

void RouteJsonObject::setAddress(std::string value) {
  m_address = value;
  m_addressIsSet = true;
}

bool RouteJsonObject::addressIsSet() const {
  return m_addressIsSet;
}



std::string RouteJsonObject::getMac() const {
  return m_mac;
}

void RouteJsonObject::setMac(std::string value) {
  m_mac = value;
  m_macIsSet = true;
}

bool RouteJsonObject::macIsSet() const {
  return m_macIsSet;
}



std::string RouteJsonObject::getInterface() const {
  return m_interface;
}

void RouteJsonObject::setInterface(std::string value) {
  m_interface = value;
  m_interfaceIsSet = true;
}

bool RouteJsonObject::interfaceIsSet() const {
  return m_interfaceIsSet;
}




}
}
}

