/**
* p4firewall API generated from p4firewall.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* FlowDirectionBase.h
*
*
*/

#pragma once

#include "../serializer/FlowDirectionJsonObject.h"






#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class P4firewall;

class FlowDirectionBase {
 public:
  
  FlowDirectionBase(P4firewall &parent);
  
  virtual ~FlowDirectionBase();
  virtual void update(const FlowDirectionJsonObject &conf);
  virtual FlowDirectionJsonObject toJsonObject();

  /// <summary>
  /// In port.
  /// </summary>
  virtual std::string getSrcInterface() = 0;

  /// <summary>
  /// Out port.
  /// </summary>
  virtual std::string getDstInterface() = 0;

  /// <summary>
  /// Inboud or outbound
  /// </summary>
  virtual uint8_t getDirection() = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  P4firewall &parent_;
};
