/**
* p4firewall API generated from p4firewall.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "FlowDirectionBase.h"
#include "../P4firewall.h"


FlowDirectionBase::FlowDirectionBase(P4firewall &parent)
    : parent_(parent) {}

FlowDirectionBase::~FlowDirectionBase() {}

void FlowDirectionBase::update(const FlowDirectionJsonObject &conf) {

}

FlowDirectionJsonObject FlowDirectionBase::toJsonObject() {
  FlowDirectionJsonObject conf;

  conf.setSrcInterface(getSrcInterface());
  conf.setDstInterface(getDstInterface());
  conf.setDirection(getDirection());

  return conf;
}

std::shared_ptr<spdlog::logger> FlowDirectionBase::logger() {
  return parent_.logger();
}

