/**
* p4firewall API generated from p4firewall.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "RouteBase.h"
#include "../P4firewall.h"


RouteBase::RouteBase(P4firewall &parent)
    : parent_(parent) {}

RouteBase::~RouteBase() {}

void RouteBase::update(const RouteJsonObject &conf) {

  if (conf.macIsSet()) {
    setMac(conf.getMac());
  }
  if (conf.interfaceIsSet()) {
    setInterface(conf.getInterface());
  }
}

RouteJsonObject RouteBase::toJsonObject() {
  RouteJsonObject conf;

  conf.setAddress(getAddress());
  conf.setMac(getMac());
  conf.setInterface(getInterface());

  return conf;
}

std::shared_ptr<spdlog::logger> RouteBase::logger() {
  return parent_.logger();
}

