/**
* p4firewall API generated from p4firewall.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

#include "api/P4firewallApiImpl.h"
#include "../datamodel/p4firewall.h" // generated from datamodel

#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "GIT_REPO_ID"

#include <polycube/services/shared_library.h>

extern "C" const char *data_model() {
  return p4firewall_datamodel.c_str();
}
